### PR TITLE
Add CHANGELOG

### PR DESCRIPTION
**Pull request by maurolacy**
Adding a changelog, same as in babylon.

### CODE REVIEW

**Comment by maurolacy** [comment]
I think we can stick to this Changelog format for the time being. The project is being actively maintained, and the results and format are not bad.

**Review by SebastianElvis — APPROVED** [review]

**Review by gitferry — APPROVED** [review]
Nice!

**Comment by SebastianElvis** [comment]
Probably we can add Makefile entries for this as well

**Comment by maurolacy** [comment]
> Probably we can add Makefile entries for this as well

Sure, will do in a follow-up.

**Pull request merged**
